---
- name: 🐛 bug
  color: "#FDC705"
  description: Something isn't working, or a fix is proposed

- name: 🎲 can't reproduce
  color: "#cfd3d7"
  description: Root cause not from project

- name: 🆙 changelog
  color: "#C2E0C6"
  description: Keep track of changes

- name: 🤖 ci
  color: "#A4A837"
  description: Continuous integration, tests, automation and management of the project

- name: 📦 dependencies
  color: "#AAA666"
  description: Update of dependencies

- name: 📚 documentation
  color: "#006b75"
  description: Update to non-code (readme, docstrings, typos, …)

- name: 🧑‍🤝‍🧑 duplicate
  color: "#cfd3d7"
  description: This issue or pull request already exists

- name: ✨ enhancement
  color: "#1870E3"
  description: Improvement or change to an existing feature

- name: 🎁 feature request
  color: "#84b6eb"
  description: Not existing yet and need to be implemented

- name: 🌱 good first issue
  color: "#B3CD7F"
  description: A place for newcomers to start contributing

- name: 🙏 help wanted
  color: "#C2E0C6"
  description: I can't do this alone and need contributors

- name: ❔ question
  color: "#d876e3"
  description: Further information is requested

- name: 💣 security
  color: "#F83911"
  description: Exploit, token leaks, …

- name: 💖 sponsor
  color: "#D3B3F2"
  description: A sponsor is involved

- name: 🔀 needs rebase or merge
  color: "#ff6b6b"
  description: PR has merge conflicts and needs to be rebased or merged

- name: 🚫 wont do/fix
  color: "#cfd3d7"
  description: This will not be worked on

- name: 🐍 compat:python
  color: "#306998"
  description: Python version compatibility work (link to the compat milestone)

- name: 🟩 compat:django
  color: "#0C4B33"
  description: Django version compatibility work (link to the compat milestone)

- name: 🧹 deprecation-cleanup
  color: "#5319E7"
  description: Remove code deprecated in the version targeted by the compat milestone
