---
"🆙 changelog":
  - .github/workflows/changelog.yaml
  - .github/workflows/release.yaml
  - CHANGELOG.md

"🤖 ci":
  - .github/**/*
  - .github/workflows/release.yaml
  - pyproject.toml
  - .gitignore

"📦 dependencies":
  - .github/workflows/upgrade-dependency.yaml
  - .github/dependabot.yaml
  - requirements/*
  - poetry.lock
  - pyproject.toml

"📚 documentation":
  - .github/**/*label*
  - .github/workflows/docs.yaml
  - .github/code-of-conduct.md
  - docs/**/*
  - .mailmap
  - LICENSE
  - README.md

"💖 sponsor":
  - .github/funding.yml