---
name: Auto Approve PR

on:
  workflow_call:
  pull_request_target:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]' || github.actor == 'pre-commit-ci[bot]' || github.actor == 'dlrsp-bot'
    steps:
      - name: Approve Bot PRs
        uses: hmarr/auto-approve-action@v3.2.1
        with:
          github-token: ${{ secrets.BOT_PAT }}
