---
name: Rebase PR (push)
on:
  workflow_call:
  push:
    branches: [main]
jobs:
  rebase-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v3.1.0
        with:
          base: main
          token: ${{ secrets.BOT_PAT }}
