---
name: Rebase PR (push)
on:
  workflow_call:
  push:
    branches: [main]
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v2
        with:
          base: main
          token: ${{ secrets.BOT_PAT }}
