---
name: Pull Request Recap

on:
  pull_request:
    types: [opened]

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - name: Recap changes
        if: github.actor == 'dlrsp-bot'
        uses: flowwer-dev/recap@main
        with:
          openai-apikey: ${{ secrets.OPENAI_APIKEY }}
          publish-as: DESCRIPTION
