# File: .github/workflows/upgrade-dependencies.yml
# Reference: https://www.oddbird.net/2022/06/01/dependabot-single-pull-request/
---
name: Upgrade dependencies

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'requirements/*.in'
  schedule:
    # Runs every Monday at 8:00 UTC
    - cron: '0 8 * * *'

jobs:
  upgrade:
    name: Upgrade & Open Pull Request
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        django-version: [ "3.2", "4.2" ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set Python and Django version's file variable
        run: |
          RAW_PY_ENV="py${{ matrix.python-version }}"
          RAW_DJANGO_ENV="${RAW_PY_ENV}-django${{ matrix.django-version }}"
          echo "PY_ENV=${RAW_PY_ENV//./}" >> "$GITHUB_ENV"
          echo "DJANGO_ENV=${RAW_DJANGO_ENV//./}" >> "$GITHUB_ENV"

      - name: Upgrade Python dependencies ${{ matrix.python-version }}
        run: |
          typeset -A ranges=(["3.2"]="Django>=3.2a1,<3.3" ["4.2"]="Django>=4.2,<4.3")
          pip install -U pip pip-tools
          pip-compile --upgrade --generate-hashes --allow-unsafe \
                      -P "${ranges["${{ matrix.django-version }}"]}" \
                      -o "requirements/${{ env.DJANGO_ENV }}.txt" \
                      requirements/requirements.in
          if [[ -f "requirements/dev.in" ]] ; then
            pip-compile --upgrade --generate-hashes --allow-unsafe \
                      -o requirements/${{ env.PY_ENV }}-dev.txt \
                      requirements/dev.in
          fi
          if [[ "${{ matrix.python-version }}" == "3.11" ]] ; then
            if [[ -f "requirements/docs.in" ]] ; then
              pip-compile --upgrade --generate-hashes --allow-unsafe \
                      -o requirements/py-docs.txt \
                      requirements/docs.in
            fi
          fi

      - name: Upload Python dependencies ${{ matrix.python-version }} for Django ${{ matrix.django-version }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DJANGO_ENV }}.txt
          path: requirements/${{ env.DJANGO_ENV }}.txt

      - name: Upload Python dependencies ${{ matrix.python-version }} for Dev ${{ matrix.django-version }}
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          name: ${{ env.PY_ENV }}-dev.txt
          path: requirements/${{ env.PY_ENV }}-dev.txt

      - name: Upload Python dependencies ${{ matrix.python-version }} for Docs
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          name: docs.txt
          path: requirements/py-docs.txt

  pull-request:
    name: Open Pull Request
    runs-on: ubuntu-latest
    needs: upgrade
    env:
      BRANCH_NAME: auto-dependency-upgrades-py-django
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: py*
#      - run: ls -R *
#
#      - name: Removing old files
#        run: |
#          for X_Dir in "tmp_artifacts/"*
#          do
#            echo "Move file from [${X_Dir}] to requirements/"
#            mv -f "${X_Dir}"/* requirements/
#          done
#          rm -rf tmp_artifacts && echo "Temporary directory deleted!"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_PAT }}
          commit-message: "Automated dependency upgrades"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          title: 'Automated dependency upgrades'
          body: "Full log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          labels: |
            📦 dependencies
            python
          assignees: ${{ github.actor }}
          draft: false
